### PR TITLE
DO NOT MERGE (lio)

### PR DESCRIPTION
**Pull request by fisx**
Here are a few ideas on how `lio` can be used more conveniently.

I will keep track of our off-band discussion here until we reach a conclusion.

### CODE REVIEW

**Comment by ChristianSi** [comment]
I'm don't yet see how we're supposed to define safe actions, i.e. how to actually use LIO for authorization control.

**Comment by fisx** [comment]
```haskell
safeFreshServiceId = makeActionSafe unsafeFreshServiceId
safeLookupConfirmedUser uid = withUserHasId uid $ unsafeLookupConfirmedUser uid
```

In practice, you would probably inline `unsafeLookupConfirmedUser` so you have one function for this action as before:

```haskell
lookupConfirmedUser :: UserId -> Action e (UserId, User)
lookupConfirmedUser uid = withUserHasId uid $
  _lookupUser $ T.lookupConfirmedUser uid
```

Does that help?

**Comment by ChristianSi** [comment]
@fisx:

> Does that help?

Yes, looks nice enough.

How to combine multiple conditions (OR or AND)? And what happens if the condition is not fulfilled, does that depend on the `with...` function or can it be controlled by the action?

**Comment by fisx** [comment]
I answered your two questions with two commits, in reverse order.

Re OR, AND: call `makeActionSafe'` with a predicate provided at the end of the module.

(sorry, i just push-forced.)

**Comment by ChristianSi** [comment]
That's means for each predicate (e.g. `withUserHasRole`) we would need a `...Catch` alternative? That sounds a bit inflexible to me.

**Comment by fisx** [comment]
of course you can just use `Action` as a `MonadError` and do things as originally intended...

**Comment by fisx** [comment]
closing in favour of #341

**Pull request closed without merging**
