### PR TITLE
hw service: store service session token in cookie when returning from…

### PR DESCRIPTION
**Pull request by fhartwig**
… thentos login

### CODE REVIEW

**Comment by fhartwig** [comment]
For some reason, the hw service currently doesn't notice when the user logs out of thentos. I suspect that this is a bug in thentos, though. Will investigate.

**Comment by mf59816** [comment]
if you mean "hw doesn't notice if user logs out of thentos", then i can explain: thentos clears the DB on user logout, but it doesn't notify the service.  it doesn't even have a channel for that; hw would need to ask thentos if the service session token is still valid, but i haven't found that happening anywhere either.

Am I talking about the same thing as you?

**Comment by fhartwig** [comment]
@mf59816 Yes, we're talking about the same thing. `verifyToken` is called by every request to the hw service, and it should return `False` if the session doesn't exist any more. But that doesn't seem to happen.

**Comment by fhartwig** [comment]
update: service sessions aren't cleaned up when a thentos session is deleted. Fixing.

**Pull request merged**
