### PR TITLE
Allow frontend actions to run with elevated privileges when necessary

### LINKED ISSUE #105: Provide variants `snapRunActionE'P`, `snapRnuAction'P`.
These must execute the action with top clearance.  We need this when registering a user at the point where the user has been added to `dbUsers` and is about to receive her roles.  But there are probably other situations as well.

### PR DESCRIPTION
**Pull request by fhartwig**
Fixes #105 
Note that this pr is for 2015-05-27-fh-hspec-weirdness, not for master, as discussed.
Also, the tests now pass again (modulo non-deterministic selenium tests). Yay us!

### CODE REVIEW

**Comment by mf59816** [comment]
There is some connection to the changes I requested in #106.  Now I think you should probably merge #106 and implement those changes here.

I think with my comments processed, I'll be happy with all this.  (-:

**Comment by fhartwig** [comment]
@mf59816 Do you thing the error handling is ok now?

**Comment by mf59816** [comment]
If travis and you are happy, please merge.

**Comment by fhartwig** [comment]
Looks good. Tests pass locally.

**Pull request merged**
