### PR TITLE
Move sso-related db fields, transactions and actions into thentos-adhocracy

### PR DESCRIPTION
**Pull request by fhartwig**
This is basically a refactoring for #212 , but since it's nice and self-contained I'd like to merge it before the actual implementation work.

### CODE REVIEW

**Comment by jkarni** [comment]
Just so I understand - why move it to `thentos-adhocracy`?

**Comment by fhartwig** [comment]
@jkarni Because that's the only place we actually want to use sso. The SSO module lives in that package, the transactions & actions were just in core for historical reasons.

**Comment by jkarni** [comment]
Ok, I'm going to wait on travis, but otherwise LGTM

**Comment by fhartwig** [comment]
@jkarni Sorry, forgot to add the new file. Fixing now...

**Pull request merged**
