### PR TITLE
2016 12 07 captcha

### PR DESCRIPTION
**Pull request by ssadler**
This PR is slightly unfinished, there's 2 things to address:

The size of the captcha*, and maybe error handling**. For some reason I couldn't figure out the correct width looking at the old code and I have to leave now but it's an easy change.

Sorry it's a bit of a messy PR (blame it on Friday), also need to delete my test script!

Cheers

* https://github.com/liqd/thentos/compare/master...ssadler:2016-12-07-captcha?expand=1#diff-16ffd6018aba3714969367948e41f0a2R44

* https://github.com/liqd/thentos/compare/master...ssadler:2016-12-07-captcha?expand=1#diff-16ffd6018aba3714969367948e41f0a2R29

### CODE REVIEW

**Comment by fisx** [comment]
@ssadler commencing review!

I've also invited you to the liqd employee team.  If you push your branches to liqd/thentos in the future, I can commit small fixes during the review myself.  For this one, I'll stick to comments here.

**Comment by fisx** [comment]
travis has hlint errors.  to reproduce locally:

```shell
make hlint
```

or

```shell
./misc/thentos-install.hs -p -t
```

(`-h` will explain that `-t` means thorough)

**Comment by ssadler** [comment]
Script I was using to test:


    module Mkcap (img) where

    import Control.Monad (forM_)
    import Data.ByteString as BS
    import Data.String.Conversions
    import Thentos.Sybil
    import Thentos.Types


    img :: IO ()
    img = do
        let baseNum = 11234597890123456789
        forM_ [0..20] $ \n -> do
            let Just rnd = mkRandom20 $ cs $ show $ baseNum + n
            (ImageData pngData, solution) <- generateCaptcha rnd
            let path = "/host/tmp/" ++ cs solution ++ ".png"
            BS.writeFile path pngData

**Comment by fisx** [comment]
Looks good, thanks!  Made a few changes and merged into #446 (a58d946..04b7692).

**Pull request closed without merging**
