### PR TITLE
Refactoring in Thentos.Transaction and Thentos.Backend.Api.SimpleSpec

### PR DESCRIPTION
**Pull request by np**
* Thentos.Transaction: add and use a more flexible variation of returnUnique
* Thentos.Backend.Api.SimpleSpec: use shouldRespondWith more often

### CODE REVIEW

**Comment by fisx** [comment]
Nice.  I like PRs that remove more lines than they add.

**Comment by fisx** [comment]
Can you fix the typo (if it is one) and merge yourself?

**Comment by fisx** [comment]
Travis needs to be run again (selenium is a bit shaky), and the `NOPE` is still there, I think.  Otherwise ready to merge.

**Comment by np** [comment]
My analysis was wrong as I didn't yet look at `catcher` in Thentos.Transaction.Core

**Comment by fisx** [comment]
Erm, but that's not what happens here, no?  You get back a list of 0, 1, or many entries from sql, not an error.

**Comment by fisx** [comment]
Ok, got it, you are right.  The comment was correct.  Can you revert this?

**Comment by fisx** [comment]
I'm bad at reading diffs, sorry.  You didn't remove the line, just the `NOPE`.

Ignore this noise.   (-:

**Pull request merged**
