### PR TITLE
Tweak purescript build script

### PR DESCRIPTION
**Pull request by fisx**

### CODE REVIEW

**Comment by fisx** [comment]
(oops, just realized i called the branch "something-something-*buildout*@.  never mind.  (-:

**Comment by fisx** [comment]
23e9a75 crashes on travis as intended; b357c89 should go through.  if it does, this pr is ready for review.

**Comment by fhartwig** [comment]
Looks good, I'm just waiting for travis.

**Comment by fisx** [comment]
(it looked good, but it was broken.  this seems more fixed...  sorry!)

**Comment by fisx** [comment]
The tests all failed because a brittle test case in the server code.  It is easy to see from the time at which travis fails in the resp. commits that it now correctly catches psc errors and compiles if there are none.

The next commit will fix the offending test case.

**Comment by fhartwig** [comment]
(Travis still failing, will push a fix in a minute).

**Pull request merged**
