### PR TITLE
Path handling (across different dev and op scenarios)

### PR DESCRIPTION
**Pull request by fisx**
The original purpose of this branch is to get rid of absolute path names in compiled executables, which I suspect are served by cabal's `getDataFileName` in the generated module `Path_package_name`.

The config type now allows for a field `root_path` that is `.` by default.  Since this is configifier, you can also use the cli or set `ROOT_PATH` in the shell environment if `.` is not adequate.

I also cleaned up the test suite to work with the new content type and create databases and action states in a more coherent way.

### CODE REVIEW

**Comment by fisx** [comment]
(travis fails because `ppa:hvr` is unresponsive.  just for an hour or so?)

**Comment by ChristianSi** [comment]
Guess my comments points to an issue that needs to be addressed (though I cannot currently see why it doesn't work), otherwise this looks good.

**Comment by fisx** [comment]
(doing some heavy re-basing again, sorry...)

**Comment by fisx** [comment]
There are still a few errors in the test suite and I would like to update the documentation when those are fixed, but other than that this PR is ready for a preliminary review.

**Comment by ChristianSi** [comment]
Looks good, please merge after warnings have been fixed.

**Pull request merged**
